### ISSUE TITLE
bug in main.py

### ISSUE THREAD

**Issue by Pranjal-SB** [SyrqxDev/Outlook-Account-Maker#1]
PS C:\Users\...> & C:/Users/.../AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/github_repos/Outlook-Account-Maker/src/main.py              
Traceback (most recent call last):
  File "c:\github_repos\Outlook-Account-Maker\src\main.py", line 2, in <module>
    from password_generator import PasswordGenerator 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'password_generator'
PS C:\Users\...>

**Comment by S409ISDAD** [comment]
im a bit late but its just pip install password_generator

**Comment by Pranjal-SB** [comment]
lol
i was very very new to python and coding then and didn't know anything much
i know now
but thanks anyway
